[project]
name = "topic-modeling"
version = "0.0.1"

[tool.setuptools.packages]
find = {}

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
plugins = "sqlmypy"

[tool.black]
line-length = 79
